### ISSUE TITLE
Error when "Connecting the agent to a build server running anywhere else"

### ISSUE THREAD

**Issue by SKART1** [alonsodomin/docker-teamcity#1]
I exceuted command: 
`docker run -d --name some_teamcity-agent -e TEAMCITY_PORT_8111_TCP_ADDR=%SOME_IP% -e TEAMCITY_PORT_8111_TCP_PORT=%SOME_PORT% alonsodomin/teamcity-agent`
expecting docker client to start and connect to my server but it was not able even to start.

Logs showed such an output:

```
sed: -e expression #1, char 32: unterminated `s' command
sed: -e expression #1, char 22: unterminated `s' command
/docker-entrypoint.sh: 8: exec: /opt/lib/teamcity-agent/bin/agent.sh run: not found
```

**Comment by alonsodomin** [comment]
The fix has been merged into master, which now represents a 9.1 build and backported into the 9.0 branch as well.

The new Docker images should be available using 9.0 or 9.1 tags int both the server and the agent. The `latest` tag is built from master so it won't be the 9.0 version as in the previous builds.
